### ISSUE TITLE
Make the server version mismatch more of a warning than an error

### ISSUE THREAD

**Issue by apockill** [aotuai/brainframe-qt#143]
Something as simple as adding a button to "Continue Anyways" would reduce user anxiety.

We've yet to have a situation where the server version actually caused an issue, and it's really awkward telling customers to select "X" to get past that window. 

This is a common occurrence during one-off deployments where a mix of v0.28 (server) and v0.27 (client) is used because newer features from v0.28 server are needed, but the newer client might not be stable yet.

**Comment by velovix** [comment]
Definitely agree. I would also say that we should completely ignore differences between the patch versions of the server and client, since we'll be incrementing the client patch version independent of the server now.

**Comment by apockill** [comment]
Oh yeah, that might be incredibly important to do before we release the 0.28.* server

**Comment by velovix** [comment]
Okay, here are some thoughts on the behavior I would like:

- `if server.major == client.major and server.minor == client.minor`: Provide no message, proceed normally.
- `if server.major == client.major and server.minor > client.minor`: Provide a soft warning saying that the server is newer than the client and some new features may be unavailable. Give the user a link to where they can upgrade, but let them easily continue. It's not a big deal.
- `if server.major == client.major and server.minor < client.minor`: Provide a harder warning saying that the client is newer than the server and this may cause instability. Give the user a link to where they can upgrade the server and suggest they close the client, but give them a button to continue.
- `if server.major != client.major`: Provide a very hard warning saying that the client and server are completely incompatible. Strongly suggest that they close the client, but give them a button to continue.

Does this sound reasonable?

**Comment by apockill** [comment]
I'm into it. @BryceBeagle?

It doesn't even have to be that granular to provide value. If it just showed the two values and provided a warning, It'd get us most of the way. 

Not providing an error on minor != minor is definitely important to add though.

**Comment by velovix** [comment]
> Not providing an error on minor != minor is definitely important to add though.

Minor (lol) thing but I think you meant patch != patch.

**Comment by BryceBeagle** [comment]
I think this is a good idea
