### ISSUE TITLE
Re-word client/server compatibility warning

### ISSUE THREAD

**Issue by BryceBeagle** [aotuai/brainframe-qt#173]
![image](https://user-images.githubusercontent.com/5437880/125325746-25445700-e2f6-11eb-8da0-b9a5fbbee403.png)

Currently the warning assumes that the client and server must be the same version number. Now that the client is only version-locked to major releases, the client should instead indicate what server version(s) it's compatible with instead of using its own version.

**Comment by apockill** [comment]
In https://github.com/aotuai/brainframe-qt/issues/143 we decided that removing the version minor == minor check is probably best

**Comment by BryceBeagle** [comment]
Oh right. Closing in favor of #143
