### ISSUE TITLE
File path is not displayed when toggle stream config

### ISSUE THREAD

**Issue by stephenli2000** [aotuai/brainframe-qt#201]
Add a video file on BrainFrame Client.
Then click "Toggle Stream Config". File path shows empty.

**Comment by apockill** [comment]
Hi Stephen, the file path is not stored by the server. Once the video has been uploaded, the path has no meaning any more.

**Comment by velovix** [comment]
Alex is right, but I think this is still a bit confusing. I think we should consider putting something, like `<uploaded>` in the file path field to indicate why that field doesn't have the original path. Alternatively, we could just not show the file path text field when looking at the stream config after the stream is created.
